### ISSUE TITLE
Add CancellationToken support to ProgressDialog

### ISSUE THREAD

**Issue by vpenades** [ookii-dialogs/ookii-dialogs-wpf#53]
I have a job action that is declared like this:

```c#

void MyJob(IProgress<int> progress, System.Threading.CancellationToken token)
{
    System.SomeTaskMethod(token);
}

```

And I want to use it along with ProgressDialog.

ProgressDialog already supports IProgress<int> , but I haven't seen a way to connect the CancellationToken with the ProgressDialog, so right now I'm doing something like this:

```c#
var dlg = new Ookii.Dialogs.Wpf.ProgressDialog();
                
dlg.DoWork += (s, e) =>
{
    MyJob( dlg, CancellationToken.None );
};

dlg.ShowDialog();
```

Solutions:

- Let `ProgressDialog` be configured with a `System.Threading.CancellationTokenSource`, so when the user clicks Cancel, it will propagate the cancellation to the tokens. Also add a CancellationToken to DoWorkEventArgs, so it can be used by the job.
  - if a CancellationSource is not configured, a default one should be created.
- Add a CancelJob event that can be used like:   `dlg.CancelJob += (s,e) => tokenSource.Cancel();`
- Add a virtual CancelJob method that can be overriden in a derived class.

Given that DotNet is moving towards Task and async/await, so more and more system methods are using CancellationToken, I would suggest to adopt the first solution.

PR?

**Comment by augustoproiete** [comment]
Interesting idea. I think your first suggestion would be a good fit.

Having a private `CancellationTokenSource` that can be used to expose the `CancellationToken` to `DoWork`, and that also can also be used to trigger the cancellation as a response to the user cancelling the dialog make sense to me.

The only thing I'm pondering is that it might be better (in terms of API) to allow users to provide a `CancellationToken` instead of a custom `CancellationTokenSource`.

What do you think about the following:

- Add an overload to `Show` and `ShowDialog` that can receive a `CancellationToken` 
- Always create a `CancellationTokenSource`, owned by the dialog, that is directly linked to the `CancellationToken` provided i.e. `CancellationTokenSource.CreateLinkedTokenSource`
- Expose the `CancellationToken` via `DoWorkEventArgs`

```csharp
var dlg = new Ookii.Dialogs.Wpf.ProgressDialog();
                
dlg.DoWork += (s, e) =>
{
    MyJob(dlg, e.CancellationToken);
};

dlg.ShowDialog(cancellationToken);
```

Eventually (in a future PR) we could also consider listening to the `CancellationToken` cancellation and close the dialog automatically if the job is cancelled by some event in the code and not by the user (i.e. `cancellationToken.Register(...)`).

**Comment by augustoproiete** [comment]
:tada: This issue has been resolved in **Ookii.Dialogs.Wpf v4.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/ookii-dialogs/ookii-dialogs-wpf/releases/tag/v4.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Ookii.Dialogs.Wpf/4.0.0)
